
#Equity Types (UPPER CASE ONLY !!)
EQUITY_COMMON_STOCK = "COMMON STOCK"
EQUITY_ETF = "ETF"
EQUITY_FUND = "FUND"
EQUITY_MUTUAL_FUND = "MUTUAL FUND"
EQUITY_MISC = "MISC"
PREFERRED_SHARE = "PREFERRED SHARE"